import unittest


class TestSimpleCase1(unittest.TestCase):

    def test_groups(self):
        from enties.source import Sources
        from enties.rule import Rules
        sources = Sources("files/process/sources.yaml")
        rules = Rules("files/process/rules.yaml")
        result = rules.exec(sources)
        self.assertEqual(result, {'edges': ['A.0-B.0',
                                            'A.1-B.22',
                                            'A.2-B.23',
                                            'A.3-B.24',
                                            'A.4-B.7',
                                            'A.5-B.1',
                                            'A.6-B.2',
                                            'A.7-B.3',
                                            'A.8-B.4',
                                            'A.9-B.5',
                                            'A.10-B.6',
                                            'A.11-B.13',
                                            'A.12-B.14',
                                            'A.13-B.15',
                                            'A.14-B.16',
                                            'A.15-B.17',
                                            'A.16-B.18',
                                            'A.17-B.19',
                                            'A.18-B.20',
                                            'A.19-B.21',
                                            'A.20-B.8',
                                            'A.21-B.9',
                                            'A.22-B.10',
                                            'A.23-B.11',
                                            'A.24-B.12'],
                                  'nodes': {'A': [{'id': '27475', 'name': 'Leonard', 'number': '584642300'},
                                                  {'id': '87900', 'name': 'Ashton', 'number': '819569476'},
                                                  {'id': '75204', 'name': 'Omar', 'number': '149371254'},
                                                  {'id': '69217', 'name': 'Forrest', 'number': '390573996'},
                                                  {'id': '57656', 'name': 'Oliver', 'number': '242199651'},
                                                  {'id': '29704', 'name': 'Julian', 'number': '713927028'},
                                                  {'id': '88743', 'name': 'Baxter', 'number': '306626151'},
                                                  {'id': '34784', 'name': 'Bevis', 'number': '642962898'},
                                                  {'id': '82284', 'name': 'Clark', 'number': '132621301'},
                                                  {'id': '53827', 'name': 'Henry', 'number': '292366390'},
                                                  {'id': '13435', 'name': 'Prescott', 'number': '145626354'},
                                                  {'id': '73219', 'name': 'Ahmed', 'number': '829520402'},
                                                  {'id': '39282', 'name': 'Roth', 'number': '978718328'},
                                                  {'id': '38136', 'name': 'Amery', 'number': '592717797'},
                                                  {'id': '30560', 'name': 'George', 'number': '794625459'},
                                                  {'id': '53868', 'name': 'Cyrus', 'number': '346547664'},
                                                  {'id': '87424', 'name': 'Erasmus', 'number': '266809110'},
                                                  {'id': '12090', 'name': 'Luke', 'number': '723420345'},
                                                  {'id': '75169', 'name': 'Logan', 'number': '157394305'},
                                                  {'id': '27982', 'name': 'Xander', 'number': '348708108'},
                                                  {'id': '12905', 'name': 'Tanek', 'number': '800511024'},
                                                  {'id': '55882', 'name': 'Jesse', 'number': '790180665'},
                                                  {'id': '17227', 'name': 'Jelani', 'number': '139196687'},
                                                  {'id': '69659', 'name': 'Kevin', 'number': '719115347'},
                                                  {'id': '89499', 'name': 'Thaddeus', 'number': '588030544'}],
                                            'B': [{'kind': 'a', 'serial': '584642300'},
                                                  {'kind': 'b', 'serial': '713927028'},
                                                  {'kind': 'b', 'serial': '306626151'},
                                                  {'kind': 'c', 'serial': '642962898'},
                                                  {'kind': 'd', 'serial': '132621301'},
                                                  {'kind': 'b', 'serial': '292366390'},
                                                  {'kind': 'c', 'serial': '145626354'},
                                                  {'kind': 'b', 'serial': '242199651'},
                                                  {'kind': 'a', 'serial': '800511024'},
                                                  {'kind': 'd', 'serial': '790180665'},
                                                  {'kind': 'c', 'serial': '139196687'},
                                                  {'kind': 'd', 'serial': '719115347'},
                                                  {'kind': 'b', 'serial': '588030544'},
                                                  {'kind': 'a', 'serial': '829520402'},
                                                  {'kind': 'a', 'serial': '978718328'},
                                                  {'kind': 'b', 'serial': '592717797'},
                                                  {'kind': 'a', 'serial': '794625459'},
                                                  {'kind': 'c', 'serial': '346547664'},
                                                  {'kind': 'd', 'serial': '266809110'},
                                                  {'kind': 'a', 'serial': '723420345'},
                                                  {'kind': 'b', 'serial': '157394305'},
                                                  {'kind': 'c', 'serial': '348708108'},
                                                  {'kind': 'a', 'serial': '819569476'},
                                                  {'kind': 'd', 'serial': '149371254'},
                                                  {'kind': 'd', 'serial': '390573996'}]}})
